/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package debreselam;

import javax.swing.ImageIcon;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Julie
 */
public class AddMember extends javax.swing.JFrame {

    Connection conn = null; 
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public AddMember() {
        initComponents();
        conn = db.java_db();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p_amh = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_gname = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        ImageMember = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        ImageTetery = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        r_female = new javax.swing.JRadioButton();
        r_male = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        txt_boCity = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_yeKerstenaName = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txt_domShip = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_kebele = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        txt_gradeLevel = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_TeteryName = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txt_TeteryAddress = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_TeteryOrg = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txt_TeteryPhone = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Debre Selam Beale Egziabher Sunday School");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_amh.setBackground(new java.awt.Color(255, 255, 255));
        p_amh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("ጾታ ፡");
        p_amh.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 70, -1));

        jLabel13.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("የአባት ስም ፡");
        p_amh.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 70, -1));

        jLabel16.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("የአያት ስም ፡");
        p_amh.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 70, -1));

        txt_fname.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_fname.setToolTipText("");
        p_amh.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 140, 30));

        txt_name.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_name.setToolTipText("");
        p_amh.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 140, 30));

        jLabel49.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel49.setText("ቁጥር ፡");
        p_amh.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 160, 20));

        txt_id.setEditable(false);
        txt_id.setFont(new java.awt.Font("Power Geez Unicode1", 0, 11)); // NOI18N
        txt_id.setToolTipText("");
        p_amh.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 80, 30));

        txt_gname.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_gname.setToolTipText("");
        p_amh.add(txt_gname, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 140, 30));

        jDesktopPane1.setLayer(ImageMember, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImageMember, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImageMember, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );

        p_amh.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, 120, 120));

        jDesktopPane2.setLayer(ImageTetery, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImageTetery, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImageTetery, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );

        p_amh.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 0));
        jButton1.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jButton1.setText("የተጠሪ ፎቶ ያስገቡ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        p_amh.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 210, 140, 40));

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 51));
        jButton2.setText("አባል ፎቶ ያስገቡ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        p_amh.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 140, 40));

        r_female.setBackground(new java.awt.Color(255, 255, 255));
        r_female.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        r_female.setText("ሴት");
        r_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_femaleActionPerformed(evt);
            }
        });
        p_amh.add(r_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        r_male.setBackground(new java.awt.Color(255, 255, 255));
        r_male.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        r_male.setText("ወንድ");
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });
        p_amh.add(r_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText(" ስም ፡");
        p_amh.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 70, -1));

        txt_boCity.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_boCity.setToolTipText("");
        p_amh.add(txt_boCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 210, 30));

        jLabel15.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("ዕድሜ ፡");
        p_amh.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 70, -1));

        jLabel17.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("የክርስትና ስም ፡");
        p_amh.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, -1));

        txt_yeKerstenaName.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_yeKerstenaName.setToolTipText("");
        txt_yeKerstenaName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_yeKerstenaNameActionPerformed(evt);
            }
        });
        p_amh.add(txt_yeKerstenaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, 30));

        txt_age.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_age.setToolTipText("");
        p_amh.add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 140, 30));

        jLabel40.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("የተወለደበት/ችበት ከተማ ፡");
        p_amh.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 150, -1));

        txt_domShip.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_domShip.setToolTipText("");
        p_amh.add(txt_domShip, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 210, 30));

        jLabel41.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel41.setText("የሰንበት ት/ቤት አባል የሆነበት/ችበት ጊዜ፡");
        p_amh.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 210, -1));

        txt_address.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_address.setToolTipText("");
        p_amh.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 140, 30));

        jLabel18.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("አድራሻ ፡");
        p_amh.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 70, -1));

        jLabel19.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("ቀበሌ ፡");
        p_amh.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 70, -1));

        txt_kebele.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_kebele.setToolTipText("");
        p_amh.add(txt_kebele, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 140, 30));

        jLabel20.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("ስልክ ቁጥር ፡");
        p_amh.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 70, -1));

        txt_phone.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_phone.setToolTipText("");
        p_amh.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 140, 30));

        txt_gradeLevel.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_gradeLevel.setToolTipText("");
        p_amh.add(txt_gradeLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 140, 30));

        jLabel21.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("ክፍል 1 ፡ የአባል ታሪክ");
        p_amh.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 170, 20));

        jLabel22.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("የክፍል ደረጃ ፡");
        p_amh.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 80, -1));

        jLabel23.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("የተጠሪው ስም ፡");
        p_amh.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 80, -1));

        txt_TeteryName.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_TeteryName.setToolTipText("");
        p_amh.add(txt_TeteryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 140, 30));

        jLabel24.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("የቤት አድራሻ ፡");
        p_amh.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 90, -1));

        txt_TeteryAddress.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_TeteryAddress.setToolTipText("");
        p_amh.add(txt_TeteryAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 140, 30));

        jLabel25.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("የመስ/ ቤት ስም ፡");
        p_amh.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 90, -1));

        txt_TeteryOrg.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_TeteryOrg.setToolTipText("");
        p_amh.add(txt_TeteryOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 140, 30));

        jLabel26.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("ስልክ ቁጥር ፡");
        p_amh.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 90, -1));

        txt_TeteryPhone.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_TeteryPhone.setToolTipText("");
        p_amh.add(txt_TeteryPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 140, 30));

        jLabel27.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("ክፍል 2 ፡ የተጠሪ ታሪክ");
        p_amh.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 170, 20));

        txt_date.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_date.setToolTipText("");
        p_amh.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 140, 30));

        jLabel28.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("የተመዘገበበት ቀን ፡");
        p_amh.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 100, -1));

        jPanel1.add(p_amh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 620));

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 630, 180, 40));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, 30, 30));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setForeground(new java.awt.Color(0, 51, 51));
        jButton3.setText("save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, 100, 40));

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 630, 100, 40));

        jButton5.setBackground(new java.awt.Color(255, 51, 0));
        jButton5.setForeground(new java.awt.Color(0, 51, 51));
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 630, 100, 40));

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setForeground(new java.awt.Color(0, 51, 51));
        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 630, -1, 40));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/debreselam/images/search1.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 630, 50, 40));

        jMenu1.setText("File");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/debreselam/images/home.png"))); // NOI18N
        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File jk = chooser.getSelectedFile();

        filename2 = jk.getAbsolutePath();

        //getting the width and the height of the label of the image
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename2).getImage().getScaledInstance(ImageTetery.getWidth(), ImageTetery.getHeight(), Image.SCALE_DEFAULT));
        ImageTetery.setIcon(imageIcon);

        try{

            File image = new  File(filename2);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for(int num; (num = fis.read(buf))!= -1;){
                bos.write(buf,0,num);
            }
            person_image2 = bos.toByteArray();

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File jk = chooser.getSelectedFile();

        filename1 = jk.getAbsolutePath();

        //getting the width and the height of the label of the image
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename1).getImage().getScaledInstance(ImageMember.getWidth(), ImageMember.getHeight(), Image.SCALE_DEFAULT));
        ImageMember.setIcon(imageIcon);

        try{

            File image = new  File(filename1);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for(int num; (num = fis.read(buf))!= -1;){
                bos.write(buf,0,num);
            }
            person_image1 = bos.toByteArray();

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased

    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        //confirmation
        int jk = JOptionPane.showConfirmDialog(null, "Are you sure you wanna Add new record?", "Debre Selam Beale Egziabher Sunday School" , JOptionPane.YES_NO_OPTION);

        if(jk == 0){
            try{

                String sql = "insert into Members"
                + "(name,fname,gname,yeKerstenaName,gender,"
                + " age,boCity,domShip,address,"
                + " kebele,phone,gradeLevel,date,memberPhoto,TeteryPhoto,"
                + " TeteryName,TeteryAddress,TeteryOrg,TeteryPhone) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ";
                pst = conn.prepareStatement(sql);

                // Amharic Field
                pst.setString(1, txt_name.getText());
                pst.setString(2, txt_fname.getText());
                pst.setString(3, txt_gname.getText());
                pst.setString(4, txt_yeKerstenaName.getText());
                pst.setString(5, gender);
                pst.setString(6, txt_age.getText());
                pst.setString(7, txt_boCity.getText());
                pst.setString(8, txt_domShip.getText());
                pst.setString(9, txt_address.getText());
                pst.setString(10, txt_kebele.getText());
                pst.setString(11, txt_phone.getText());

                pst.setString(12, txt_gradeLevel.getText());
                pst.setString(13, txt_date.getText());
                
                //setting the person image to database
                pst.setBytes(14, person_image1);
                //setting the person image to database
                pst.setBytes(15, person_image2);

                
                pst.setString(16, txt_TeteryName.getText());
                pst.setString(17, txt_TeteryAddress.getText());
                pst.setString(18, txt_TeteryOrg.getText());
                pst.setString(19, txt_TeteryPhone.getText());
                
                
                
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data is saved successfully");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }

            finally{
                try{
                    rs.close();
                    pst.close();
                }catch(Exception e){

                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        txt_search.setText("");
        txt_id.setText("");
        txt_name.setText("");
        txt_fname.setText("");
        txt_gname.setText("");
        txt_yeKerstenaName.setText("");
        txt_age.setText("");
        txt_boCity.setText("");
        r_male.setSelected(false);
        r_female.setSelected(false);
        txt_domShip.setText("");
  
        txt_address.setText("");

        txt_kebele.setText("");
        txt_phone.setText("");
        
        txt_gradeLevel.setText("");
        txt_date.setText("");
        
        
        //Clear Wife's image
        ImageMember.setIcon(null);

        //Clear Husband's image
        ImageTetery.setIcon(null);
        txt_TeteryName.setText("");
        txt_TeteryAddress.setText("");
        txt_TeteryOrg.setText("");
        txt_TeteryPhone.setText("");
        

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        //confirmation
        int jk = JOptionPane.showConfirmDialog(null, "Are you sure you wanna Delete the record?", "Debre Selam Beale Egziabher Sunday School" , JOptionPane.YES_NO_OPTION);

        if(jk == 0){

            //delete recored from the database where id=?

            try{

                String sql = "delete from Members where id=?";

                pst = conn.prepareStatement(sql);
                pst.setString(1, txt_id.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null, "One record deleted successfully!");

            }catch(Exception e){

                JOptionPane.showMessageDialog(null, e);

            }
            finally{

                try{

                    rs.close();
                    pst.close();

                }catch(Exception e){

                }

            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maleActionPerformed
       
        gender = "ወንድ";
        
        r_male.setSelected(true);
        r_female.setSelected(false);
        
    }//GEN-LAST:event_r_maleActionPerformed

    private void r_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_femaleActionPerformed
        
        gender = "ሴት";
        
        r_male.setSelected(false);
        r_female.setSelected(true);
        
    }//GEN-LAST:event_r_femaleActionPerformed

    private void txt_yeKerstenaNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_yeKerstenaNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_yeKerstenaNameActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       
        MainMenu ds = new MainMenu();
        ds.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

         //search by event key released

        try{

            String sql =  "select * from Members where id=?";

            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_search.getText());
            rs = pst.executeQuery();

            String add1 = rs.getString("id");
            txt_id.setText(add1);

            String add2 = rs.getString("name");
            txt_name.setText(add2);

            String add3 = rs.getString("fname");
            txt_fname.setText(add3);

            String add4 = rs.getString("gname");
            txt_gname.setText(add4);
            
            String add5 = rs.getString("yeKerstenaName");
            txt_yeKerstenaName.setText(add5);
             String gender = rs.getString("gender");   
            
            if (gender.equals("ወንድ")){
               r_male.setSelected(true);
               
        }
            else {
                 
                  r_female.setSelected(true);
                    }
            String add6 = rs.getString("age");   
            txt_age.setText(add5);
            
            String add7 = rs.getString("boCity"); 
            txt_boCity.setText(add7);
            
            String add8 = rs.getString("domShip"); 
            txt_domShip.setText(add8);
            
            String add9 = rs.getString("address"); 
            txt_address.setText(add9);
            
            String add10 = rs.getString("kebele"); 
            txt_kebele.setText(add10);
            
            String add11 = rs.getString("phone"); 
            txt_phone.setText(add11);
            
            String add12 = rs.getString("gradeLevel"); 
            txt_gradeLevel.setText(add12);
            
            String add13 = rs.getString("date"); 
            txt_date.setText(add13);
                
              
           

            String add16 = rs.getString("TeteryName");  
            txt_TeteryName.setText(add16);
            
            String add17 = rs.getString("TeteryAddress"); 
                txt_TeteryAddress.setText(add17);
                
                String add18 = rs.getString("TeteryOrg"); 
                txt_TeteryOrg.setText(add18);
                
                String add19 = rs.getString("TeteryPhone"); 
                txt_TeteryPhone.setText(add19);
                
            //dispalying Wife's image from sqlite db
            byte[] imageW = rs.getBytes("memberPhoto");
            ImageIcon imageIconW = new ImageIcon(new ImageIcon(imageW).getImage().getScaledInstance(ImageMember.getWidth(), ImageMember.getHeight(), Image.SCALE_DEFAULT));
            ImageMember.setIcon(imageIconW);

            //dispalying Husband's image from sqlite db
            byte[] imageH = rs.getBytes("TeteryPhoto");
            ImageIcon imageIconH = new ImageIcon(new ImageIcon(imageH).getImage().getScaledInstance(ImageTetery.getWidth(), ImageTetery.getHeight(), Image.SCALE_DEFAULT));
            ImageTetery.setIcon(imageIconH);

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{

            try{

                rs.close();
                pst.close();

            }catch(Exception e){

            }

        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageMember;
    private javax.swing.JLabel ImageTetery;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel p_amh;
    private javax.swing.JRadioButton r_female;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JTextField txt_TeteryAddress;
    private javax.swing.JTextField txt_TeteryName;
    private javax.swing.JTextField txt_TeteryOrg;
    private javax.swing.JTextField txt_TeteryPhone;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_boCity;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_domShip;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_gname;
    private javax.swing.JTextField txt_gradeLevel;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_kebele;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_yeKerstenaName;
    // End of variables declaration//GEN-END:variables

     private ImageIcon format1 = null;
    String filename1 = null;
    byte[] person_image1 = null;
    
    private ImageIcon format2 = null;
    String filename2 = null;
    byte[] person_image2 = null;
    
    private String gender = null;
}
