/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package debreselam;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Julie
 */
public class ViewForm extends javax.swing.JFrame {

   Connection conn = null; 
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public ViewForm() {
        initComponents();
        conn = db.java_db();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_info = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_id = new javax.swing.JLabel();
        txt_name = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        dd = new javax.swing.JDesktopPane();
        TeteryPhoto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txt_yeKerestenaName = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txt_age = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txt_gender = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_boCity = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_domShip = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txt_address = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txt_kebele = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txt_phone = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txt_gradeLevel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_amhWname10 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txt_TeteryAddress = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_TeteryOrg = new javax.swing.JLabel();
        txt_TeteryPhone = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txt_name2 = new javax.swing.JLabel();
        txt_TeteryName = new javax.swing.JLabel();
        txt_TeteryName2 = new javax.swing.JLabel();
        txt_amhWname17 = new javax.swing.JLabel();
        txt_amhWname18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txt_name3 = new javax.swing.JLabel();
        txt_amhWname20 = new javax.swing.JLabel();
        txt_amhWname21 = new javax.swing.JLabel();
        txt_amhWname22 = new javax.swing.JLabel();
        txt_amhWname23 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        f = new javax.swing.JDesktopPane();
        memberPhoto = new javax.swing.JLabel();
        txt_amhWname24 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        p_info.setBackground(new java.awt.Color(255, 255, 255));
        p_info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nyala", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("የደ/ሰ/በዓለ እግዚአብሔር ቤተ ክርስቲያን ሰ/ት/ቤት የህጻናት ፎርም");
        p_info.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 420, 20));

        jLabel3.setFont(new java.awt.Font("Nyala", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("በኢትዮጵያ ኦርቶዶክስ ተዋህዶ ቤተክርስቲያን በባህር ዳር ሀገረ ስብከት");
        p_info.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 20));

        jLabel5.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("ቁጥር ፡ ");
        p_info.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 60, 10));

        jLabel6.setFont(new java.awt.Font("Nyala", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("\" ጎልማሳ መንገዱን በምን ያንጻል ቃልህን በመጠበቅ  ነው\" መዝ. 118-9");
        p_info.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 420, -1));

        jLabel12.setFont(new java.awt.Font("Nyala", 1, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("ክፍል 3 የተጠሪው ፈቃደኝነት ማረጋገጫ");
        p_info.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 290, 20));

        txt_id.setText(".......................");
        p_info.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 100, 20));

        txt_name.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_name.setText("..........................................................................................");
        p_info.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 280, -1));
        p_info.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 110, 60));

        dd.setLayer(TeteryPhoto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ddLayout = new javax.swing.GroupLayout(dd);
        dd.setLayout(ddLayout);
        ddLayout.setHorizontalGroup(
            ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TeteryPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        ddLayout.setVerticalGroup(
            ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TeteryPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        p_info.add(dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 80, 100));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Nyala", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("የሰ/ት/ቤቱ አባላት ታሪክ መሙያ ቅጽ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_info.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 360, 20));

        jLabel7.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("ቀን ፡");
        p_info.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 60, 10));

        txt_date.setText(".......................");
        p_info.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 100, 20));

        jLabel18.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("ሙሉ ስም ከነአያት ፡");
        p_info.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 170, -1));

        jLabel33.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("የክርስትና ስም ፡");
        p_info.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, -1));

        txt_yeKerestenaName.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_yeKerestenaName.setText("..........................................................................................");
        p_info.add(txt_yeKerestenaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 280, -1));

        jLabel34.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("ዕድሜ ፡");
        p_info.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 170, -1));

        txt_age.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_age.setText("..........................................................................................");
        p_info.add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 110, -1));

        jLabel35.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("ጾታ ፡");
        p_info.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 40, -1));

        txt_gender.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_gender.setText("..........................................................................................");
        p_info.add(txt_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 110, -1));

        jLabel19.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("የተወለደበት/ችበት ከተማ ፡");
        p_info.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 170, -1));

        txt_boCity.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_boCity.setText("..........................................................................................");
        p_info.add(txt_boCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 280, -1));

        jLabel20.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("የሰንበት ት/ቤት አባል የሆነበት/ችበት ጊዜ");
        p_info.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 200, -1));

        txt_domShip.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_domShip.setText("..........................................................................................");
        p_info.add(txt_domShip, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 260, -1));

        jLabel36.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("አድራሻ ፡");
        p_info.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 170, -1));

        txt_address.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_address.setText("..........................................................................................");
        p_info.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 130, -1));

        jLabel37.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("ቀበሌ ፡");
        p_info.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 50, -1));

        txt_kebele.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_kebele.setText("..........................................................................................");
        p_info.add(txt_kebele, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 130, -1));

        jLabel38.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("ስ.ቁ ፡");
        p_info.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 50, -1));

        txt_phone.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_phone.setText("..........................................................................................");
        p_info.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 130, -1));

        jLabel39.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel39.setText("የክፍል ደረጃ ፡");
        p_info.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 170, -1));

        txt_gradeLevel.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_gradeLevel.setText("..........................................................................................");
        p_info.add(txt_gradeLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 130, -1));

        jLabel13.setFont(new java.awt.Font("Nyala", 1, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("ክፍል 1 የአባል ታሪክ");
        p_info.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 160, 20));

        jLabel21.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("የተጠሪ ስም ፡");
        p_info.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 170, -1));

        txt_amhWname10.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_amhWname10.setText("ከህያው እግዚአብሔር በተሰጠኝ አደራ መሰረት ልጄ የሰ/ት/ቤት አባል እንዲሆን/ድትሆን ፈቅጃለሁ፡፡");
        p_info.add(txt_amhWname10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 470, -1));

        jLabel40.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("የቤት አድራሻ ፡");
        p_info.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 170, -1));

        txt_TeteryAddress.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_TeteryAddress.setText("..........................................................................................");
        p_info.add(txt_TeteryAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 280, -1));

        jLabel22.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("የመስሪያ ቤት ስም ፡");
        p_info.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 170, -1));

        txt_TeteryOrg.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_TeteryOrg.setText("..........................................................................................");
        p_info.add(txt_TeteryOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 280, -1));

        txt_TeteryPhone.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_TeteryPhone.setText("..........................................................................................");
        p_info.add(txt_TeteryPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 280, -1));

        jLabel41.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel41.setText("ስ.ቁ ፡");
        p_info.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 170, -1));

        jLabel14.setFont(new java.awt.Font("Nyala", 1, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("ክፍል 2 የተጠሪ ታሪክ");
        p_info.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 160, 20));

        jLabel42.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel42.setText("እኔ አቶ/ወሮ/ወሪ/ት  ");
        p_info.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 100, -1));

        txt_name2.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_name2.setText("..........................................................................................");
        p_info.add(txt_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 100, -1));

        txt_TeteryName.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_TeteryName.setText("..........................................................................................");
        p_info.add(txt_TeteryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 280, -1));

        txt_TeteryName2.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_TeteryName2.setText("..........................................................................................");
        p_info.add(txt_TeteryName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 100, -1));

        txt_amhWname17.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_amhWname17.setText("ፈጣሪ ዓለማትን ጌታችን መድኃኒታችን ኢየሱስ ክርስቶስ በማቴዎስ ወንጌል 19-14 ላይ \"ህጻናት ወደ እኔ የምጡ ዘንድ ተዋቸው\" ብሎ እንዳዘዘው ልጄ  ");
        p_info.add(txt_amhWname17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 710, -1));

        txt_amhWname18.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_amhWname18.setText("የኦርቶዶክስ ተዋህዶ ሃይማኖት ሥርዓት እየተማረ/ች በመንፈስ ቅዱስ ኃይል ብቃለ እግዚአብሔር እንዲጎለምስ/እንድትጎለምስ በክርስቲያንነቴ ");
        p_info.add(txt_amhWname18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 730, -1));

        jLabel15.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("ሰላመ እግዚአብሔር ከሁላችን ጋር ይሁን፡፡ አሜን");
        p_info.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 680, 330, 20));

        jLabel43.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel43.setText("እኔ  ");
        p_info.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 30, -1));

        txt_name3.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_name3.setText("..........................................................................................");
        p_info.add(txt_name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 100, -1));

        txt_amhWname20.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_amhWname20.setText("በመጽሐፈ መክብብ 12-1 ላይ \"የጭንቅ ቀን ሳይመጣ በጉብዝናህ ወራት ፈጣሪህን አስብ\"  ባለው መሰረት ቀጥተኛውን የኦርቶዶክስ ተዋህዶ ");
        p_info.add(txt_amhWname20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 690, -1));

        txt_amhWname21.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_amhWname21.setText("ቤተ ክርስቲያን ሕግ እና ሥርዓት ተምሬ በሃይማኖት በመጽናት የተዋህዶ ቤተ ክርስቲያናችንን በተቻለ መጠን ለማገልገልና ለመርዳት ሙሉ ፈቃደኛ ሆኜ የዚህ  ");
        p_info.add(txt_amhWname21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 830, -1));

        txt_amhWname22.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_amhWname22.setText("በህያው እግዚአብሔር ስም ቃል ገብቻለሁ፡፡");
        p_info.add(txt_amhWname22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 830, -1));

        txt_amhWname23.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_amhWname23.setText("..........................................................................................");
        p_info.add(txt_amhWname23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 680, 100, -1));

        jLabel44.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel44.setText("ፊርማ ፡");
        p_info.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 50, -1));

        jLabel16.setFont(new java.awt.Font("Nyala", 1, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("ክፍል 4 መንፈሳዊ ቃል ኪዳን");
        p_info.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 290, 20));

        f.setLayer(memberPhoto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout fLayout = new javax.swing.GroupLayout(f);
        f.setLayout(fLayout);
        fLayout.setHorizontalGroup(
            fLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(memberPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        fLayout.setVerticalGroup(
            fLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(memberPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        p_info.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 100));

        txt_amhWname24.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt_amhWname24.setText("ሰ/ት/ቤት አባል ለመሆን ፍላጎቴ አስገድዶኝ የተመዘገብኩ መሆኔን ሳረጋግጥ በሰ/ት/ቤቱ መተዳደሪያ ደንብ መሰረት ከእኔ የሚፈለግብኝን ሁሉ ለመፈጸም ");
        p_info.add(txt_amhWname24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 830, -1));

        jButton2.setFont(new java.awt.Font("Nyala", 0, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/debreselam/images/search1.png"))); // NOI18N
        jButton2.setText("ፈልግ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Nyala", 0, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/debreselam/images/print.png"))); // NOI18N
        jButton1.setText("ፕሪንት");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("MainMenu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(53, 53, 53)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(p_info, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 66, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(710, 710, 710))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 45, Short.MAX_VALUE)
                    .addComponent(p_info, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
                
         //search by event key released
        
        try{
        
            String sql =  "select * from Members where id=?";
            
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_search.getText());
            rs = pst.executeQuery();
            
               String add1 = rs.getString("id");
               txt_id.setText(add1);
               
               String add2 = rs.getString("date");
               txt_date.setText(add2);
               
               String add3 = rs.getString("name");
               String add4 = rs.getString("fname");
               String add5 = rs.getString("gname");
               txt_name.setText(add3 +" "+ add4 + " "+ add5);
               
               String add6 = rs.getString("yeKerstenaName");
               txt_yeKerestenaName.setText(add6);
               
               String add7 = rs.getString("boCity");
               txt_boCity.setText(add7);
               
               String add21 = rs.getString("age");
               txt_age.setText(add21);
               
               String add8 = rs.getString("domShip");
               txt_domShip.setText(add8);
               
               String add9 = rs.getString("address");
               txt_address.setText(add9);
               
               String add10 = rs.getString("kebele");
               txt_kebele.setText(add10);
               
               String add11 = rs.getString("phone");
               txt_phone.setText(add11);
               
               String add12 = rs.getString("gender");
               txt_gender.setText(add12);
               
               String add13 = rs.getString("gradeLevel");
               txt_gradeLevel.setText(add13);
               
               String add14 = rs.getString("TeteryName");  
               txt_TeteryName.setText(add14);
               
               String add15 = rs.getString("TeteryAddress");
               txt_TeteryAddress.setText(add15);
               
               String add16 = rs.getString("TeteryOrg");
               txt_TeteryOrg.setText(add16);
               
               String add17 = rs.getString("TeteryPhone");
               txt_TeteryPhone.setText(add17);
               
               String add18 = rs.getString("TeteryName");
               txt_TeteryName2.setText(add18);
               
               String add19 = rs.getString("name");
               txt_name2.setText(add19 + " " + add4 + " " + add5);
               
               String add20 = rs.getString("name");
               txt_name3.setText(add20 + " " + add4 + " " + add5);
             
               
//               //displaying the radio buttons accordingly
//               String add20 = rs.getString("Gender1");
//                 if(add20.equals("ወንድ")){
//                    txt_amhSex.setText("ወንድ");
//                 }else{
//                    txt_amhSex.setText("ሴት");
//                 }
//                 
               
             //dispalying Wife's image from sqlite db
               byte[] imageW = rs.getBytes("memberPhoto");
               ImageIcon imageIconW = new ImageIcon(new ImageIcon(imageW).getImage().getScaledInstance(memberPhoto.getWidth(), memberPhoto.getHeight(), Image.SCALE_DEFAULT));
               memberPhoto.setIcon(imageIconW);
            
               
               //dispalying Husband's image from sqlite db
               byte[] imageH = rs.getBytes("TeteryPhoto");
               ImageIcon imageIconH = new ImageIcon(new ImageIcon(imageH).getImage().getScaledInstance(TeteryPhoto.getWidth(), TeteryPhoto.getHeight(), Image.SCALE_DEFAULT));
               TeteryPhoto.setIcon(imageIconH);
            

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{

            try{

                rs.close();
                pst.close();

            }catch(Exception e){

            }

        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       
        MainMenu ds = new MainMenu();
        ds.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try {
    Toolkit tkp = p_info.getToolkit();
    PrintJob pjp = tkp.getPrintJob(this, null, null);
    Graphics g = pjp.getGraphics();
    
    p_info.print(g);
    g.dispose();
   
    pjp.end();
    
     JOptionPane.showMessageDialog(null, "Successfully Printed!");
            
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TeteryPhoto;
    private javax.swing.JDesktopPane dd;
    private javax.swing.JDesktopPane f;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel memberPhoto;
    private javax.swing.JPanel p_info;
    private javax.swing.JLabel txt_TeteryAddress;
    private javax.swing.JLabel txt_TeteryName;
    private javax.swing.JLabel txt_TeteryName2;
    private javax.swing.JLabel txt_TeteryOrg;
    private javax.swing.JLabel txt_TeteryPhone;
    private javax.swing.JLabel txt_address;
    private javax.swing.JLabel txt_age;
    private javax.swing.JLabel txt_amhWname10;
    private javax.swing.JLabel txt_amhWname17;
    private javax.swing.JLabel txt_amhWname18;
    private javax.swing.JLabel txt_amhWname20;
    private javax.swing.JLabel txt_amhWname21;
    private javax.swing.JLabel txt_amhWname22;
    private javax.swing.JLabel txt_amhWname23;
    private javax.swing.JLabel txt_amhWname24;
    private javax.swing.JLabel txt_boCity;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_domShip;
    private javax.swing.JLabel txt_gender;
    private javax.swing.JLabel txt_gradeLevel;
    private javax.swing.JLabel txt_id;
    private javax.swing.JLabel txt_kebele;
    private javax.swing.JLabel txt_name;
    private javax.swing.JLabel txt_name2;
    private javax.swing.JLabel txt_name3;
    private javax.swing.JLabel txt_phone;
    private javax.swing.JTextField txt_search;
    private javax.swing.JLabel txt_yeKerestenaName;
    // End of variables declaration//GEN-END:variables
}
